/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.reactiveminds.datagrid;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Node {
    public static void main(String[] args) {
		SpringApplication.run(Node.class, args);
	}
}
